### ISSUE TITLE
every time i build the app by android studio i get this red screen error  

### ISSUE THREAD

**Issue by haysamelmasry** [inspireui/mstore#44] opened 2017-08-24 13:01 UTC
unable to load script from assets ïndex.android.bundle'. make sure your bundle is packaged correctly or you're running a package server. 
like this pic 
![screenshot_20170824-145617](https://user-images.githubusercontent.com/7470531/29667486-e11c3f92-88dc-11e7-91b2-d27b405c1801.png)

i need to make apk build for real phone not simulator

**Comment by inspireui** [comment] 2017-08-25 02:47
Hi, how about to run the app via cmd?
react-native run-android

**Comment by jeemok** [comment] 2017-08-28 04:03
@haysamelmasry maybe you can try to start `react-native start` in a new terminal to start your packager server, and try to run your app.

or another way would be generate all the static files to your assets folder, run:
`react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --sourcemap-output android/app/src/main/assets/index.android.map --assets-dest android/app/src/main/res/`

**Comment by Careieste** [comment] 2017-09-03 22:17
I have the same problem with Beonews. 
react-native run-android command run successfuly, but when I try to install on phone the generated apk file then I have the error from the image from first comment on this topic.
I want to publish the app on Google play.
Please help me with that.
Thank you!

**Comment by haysamelmasry** [comment] 2017-09-06 08:10
I run the app via cmd and the app works fine but how can I build it via cmd ?

**Comment by inspireui** [comment] 2017-09-27 00:57
Hi @haysamelmasry, could you check if the issue is fixed on latest version, please help to close the ticket if you have resolved the issue. Thank you!

**Closed** 2017-10-05 07:57 UTC
Labels: enhancement, help wanted

**Comment by andybedoy** [comment] 2018-02-21 17:04
for me dont work
