### ISSUE TITLE
app not read product or category

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/mstore#133] opened 2018-01-21 13:51 UTC
i pursache ur product and make all thing from documentation
test app from window read wordpress users
but dont read product or category's
i made api as u say https://www.deallak.net/wp-json/wc/v2
plzz see attachment photo
![image](https://user-images.githubusercontent.com/35544603/35194852-d05137c4-fec2-11e7-9cd9-94bce44bed6e.png)
![image](https://user-images.githubusercontent.com/35544603/35194854-e4bb05f0-fec2-11e7-97bb-e6e63ceb4d88.png)

**Comment by inspireui** [comment] 2018-01-24 08:34
Hi @mohamedibrahim89 could you share your config.js file here so that we will help to check - thank  you!

**Comment by mohamedibrahim89** [comment] 2018-01-24 08:41
import Images from "./Images"
import Constants from './Constants'

export default {
  /**
   Step 1: change to your website URL and the wooCommerce API consumeKey
   */
  WooCommerce: {
    url: 'https://deallak.net',
    consumerKey: 'ck_b93c471308607703d38f1079823ec811e5c98ed3',
    consumerSecret: 'cs_0753fcc46b3882dbda177fe69fa4f531a37b8665',
  },

  /**
   Step 2: Setting Product Images
   - ProductSize: Explode the guide from: update the product display size: https://mstore.gitbooks.io/mstore-manual/content/chapter5.html
   The default config for ProductSize is disable due to some problem config for most of users.
   If you have success config it from the Wordpress site, please enable to speed up the app performance
   - HorizonLayout: Change the HomePage horizontal layout - https://mstore.gitbooks.io/mstore-manual/content/chapter6.html
   */
  ProductSize: {
    enable: true,
    CatalogImages: {width: 585, height: 750},
    SingleProductImage: {width: 800, height: 1100},
    ProductThumbnails: {width: 172, height: 217},
  },
  HorizonLayout: [
    {tag: 9120, paging: true, layout: Constants.Layout.miniBanner},
    {name: "Clothes Collection", category: 273, image: Images.Banner.Feature, layout: Constants.Layout.threeColumn},
    {name: "Shoes Collection", category: 269, image: Images.Banner.Bag, layout: Constants.Layout.twoColumn},
    {name: "Make up collection", category: 343, image: Images.Banner.Woman, layout: Constants.Layout.twoColumnHigh},
    {name: "Bags Collection", category: 272, image: Images.Banner.Man, layout: Constants.Layout.card},
  ],

  /**
   step 3: Config image for the Payment Gateway
   Notes:
   - Only the image list here will be shown on the app but it should match with the key id from the WooCommerce Website config
   - It's flexible way to control list of your payment as well
   Ex. if you would like to show only cod then just put one cod image in the list
   **/
  Payments: {
 //   bacs: require('@images/payment_logo/PayPal.png'),
    cod: require('@images/payment_logo/cash_on_delivery.png'),
 //   paypal: require('@images/payment_logo/PayPal.png'),
 //   stripe: require('@images/payment_logo/stripe.png'),
  },

  /**
   Step 4: Advance config:
   - showShipping: option to show the list of shipping method
   - showStatusBar: option to show the status bar, it always show iPhoneX
   - LogoImage: The header logo
   - LogoWithText: The Logo use for sign up form
   - LogoLoading: The loading icon logo
   - appFacebookId: The app facebook ID, use for Facebook login
   - CustomPages: Update the custom page which can be shown from the left side bar (Components/Drawer/index.js)
   - WebPages: This could be the id of your blog post or the full URL which point to any Webpage (responsive mobile is required on the web page)
   **/
  shipping : {
    visible: true,
    time: {
      free_shipping: '4 - 7 Days',
      flat_rate: '1 - 4 Days',
      local_pickup: '1 - 4 Days',
    }
  },
  showStatusBar: false,
  LogoImage: require('@images/new_logo.png'),
  LogoWithText: require('@images/logo_with_text.png'),
  LogoLoading: require('@images/logo.png'),

  showAdmobAds: true,
  AdMob: {
    deviceID: "pub-2101182411274198",
    unitID: "ca-app-pub-2101182411274198/4100506392",
    unitInterstitial: "ca-app-pub-2101182411274198/8930161243",
    isShowInterstital: true
  },
  appFacebookId: '422035778152242',
  CustomPages: {contact_id: 10941},
  WebPages: {marketing: 'http://inspireui.com'},
};

**Comment by inspireui** [comment] 2018-01-24 10:25
Hi, your issue is the WooCommerce API is not enable so that you could not get data from the URL:
<img width="1674" alt="screen shot 2018-01-24 at 5 19 43 pm" src="https://user-images.githubusercontent.com/29778334/35327063-1f1b80b6-012b-11e8-8616-79ef6098a06e.png">

You can see the difference from:
https://www.deallak.net/wp-json/wc/v2/
and mstore.io/wp-json/wc/v2/

Solution: update your setting this this one:
<img width="955" alt="screen shot 2018-01-24 at 5 23 53 pm" src="https://user-images.githubusercontent.com/29778334/35327147-6efeb364-012b-11e8-9d72-2978ae2c1938.png">

**Comment by mohamedibrahim89** [comment] 2018-01-24 13:51
I already do that
Sorry for distrbuite but u dont know why api not send data

On 24 Jan 2018 12:25 pm, "InspireUI" <notifications@github.com> wrote:

Hi, your issue is the WooCommerce API is not enable so that you could not
get data from the URL:
[image: screen shot 2018-01-24 at 5 19 43 pm]
<https://user-images.githubusercontent.com/29778334/35327063-1f1b80b6-012b-11e8-8616-79ef6098a06e.png>

You can see the difference from:
https://www.deallak.net/wp-json/wc/v2/
and mstore.io/wp-json/wc/v2/

Solution: update your setting this this one:
[image: screen shot 2018-01-24 at 5 23 53 pm]
<https://user-images.githubusercontent.com/29778334/35327147-6efeb364-012b-11e8-9d72-2978ae2c1938.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/inspireui/mstore/issues/133#issuecomment-360086725>,
or mute
the thread

**Comment by inspireui** [comment] 2018-01-25 01:54
i have got your issues, the root cause is there are a lot of api enable from your site, you can get the list from https://www.deallak.net/wp-json

My solution is change this file config from the app - src/services/WooWorker.js
Change:   version: 'wc/v2'  to   version: 'wc/v1',

<img width="1091" alt="screen shot 2018-01-25 at 8 52 29 am" src="https://user-images.githubusercontent.com/29778334/35366696-43f6a49c-01ad-11e8-945c-e32a71c7404d.png">

**Comment by mohamedibrahim89** [comment] 2018-01-25 09:38
Ys worked thank u very much
What about payfort payment

**Comment by mohamedibrahim89** [comment] 2018-01-25 12:31
now everything is ok
app read api category's and product
but not show any image from website i attach  config.js ,omni, appi screen
shoot photo

and plz need to know if i want u to add payfort payment to app how much
will it cost
thanks in advice

[image: Inline image 4]

[image: Inline image 3]

[image: Inline image 2]
[image: Inline image 1]

**Comment by inspireui** [comment] 2018-01-29 17:04
Thank you for your confirm, allow me to close the issue as all fix.

Please contact to support team support@inspireui.com to get the quotes for payfort support - thank you!

**Closed by inspireui** 2018-01-29 17:04 UTC
Labels: help wanted
