### ISSUE TITLE
[Beonews] Undefined is not an object (evaluating 'child.type')

### ISSUE THREAD

**Issue by ItsMeSafiuddin** [inspireui/mstore#73] opened 2017-10-24 08:44 UTC
Hi, please help me with this error

![error child type](https://user-images.githubusercontent.com/10663688/31932962-5ec7210a-b8da-11e7-8f06-a525f7214240.png)

**Comment by inspireui** [comment] 2017-10-26 00:59
Hi, could i check this issue on the Mstore or BeoNews product? Thank you!

**Comment by ItsMeSafiuddin** [comment] 2017-10-26 02:27
this issue from BeoNews product

**Comment by tameryetim** [comment] 2017-10-26 11:31
Hi @inspireui 

I have the same problem

what should I do ?

Error Start -     https://gyazo.com/4da7677be8895e50a018b05309a4c8ac

Error End -       https://gyazo.com/4743b2bb80c881f98a4fef3b23e0a385

My Config.Js  -  https://gyazo.com/dc15a7b388114616db757b268b6439c4

My BeoNews Version = 2.7.1

Thanks.

**Comment by inspireui** [comment] 2017-10-29 14:43
This issue is caused by the parallax category component, please ty to map the lag category name to match with the imageCategory from images.js file - https://gyazo.com/b4b4583a4c8e72dc290bff506204ca5c

**Comment by louierosero-gss** [comment] 2017-12-27 09:52
@inspireui I'm kinda fixed this issue by commenting this specific code in ParallaxScrollViewComposition.js

`var applyPropsToParallaxImages = function (children, props) {
  if (isArray(children)) {
    return children.map(child => {
      if (isArray(child)) {
        return applyPropsToParallaxImages(child, props);
      }
      // if (child.type === ParallaxImage) {
      //   return React.cloneElement(child, props);
      // }
      return child;
    });
  }`

Anyway, can you explain to me of what would happen if I do this commenting in this condition?

**Comment by inspireui** [comment] 2017-12-27 14:00
Hi, it would be fixed on v2.8.0, please download the latest version. Thank you!

**Closed by inspireui** 2017-12-27 14:00 UTC
Labels: bug, help wanted
