### ISSUE TITLE
Problem with store configuration

### ISSUE THREAD

**Issue by Vrijlating** [inspireui/mstore#45] opened 2017-08-26 09:14 UTC
Hello,
i have a problem with a configuration for my app, I have try to follow the guide step by step, but I have encountered some problem.
First of all, just I download the project  for me is impossible to build the app with xcode because appear messages of error from Xcode and is impossible to test it, you can see it on the screen:
<img width="1440" alt="schermata 2017-08-26 alle 11 14 04" src="https://user-images.githubusercontent.com/31366135/29740137-b144a998-8a4f-11e7-9ce6-a09e4b36fbf9.png">

I have start to follow the documentation and is everything ok until the "woo commerce Settings", in fact, I am test the app on a demo woo commerce installation and there aren't products with attributes, so for this moment I don't have make nothing in this step.
About multi language, my store is located in Italian, but, just for test, I need t change it immediately in the app?
I have also try to follow the guide for migrate the service and Facebook, but from Xcode I continue to have problem to build and is impossible to test, I have attached a screen also for this
<img width="1440" alt="schermata 2017-08-26 alle 11 02 03" src="https://user-images.githubusercontent.com/31366135/29740114-63970ae2-8a4f-11e7-98bf-b0b7cd9a291f.png">

**Comment by inspireui** [comment] 2017-08-28 15:06
Hi, could you help to press the warning icon to send us the detail error log ?

You can run the app without XCode by using this cmd:
- yarn install
- react-native run-ios

Thank you!

**Comment by Vrijlating** [comment] 2017-08-29 09:37
Hello,
this is what happened when I try to run from react native
<img width="1440" alt="schermata 2017-08-29 alle 11 37 20" src="https://user-images.githubusercontent.com/31366135/29814671-74eeeaba-8cae-11e7-96a6-d72c61d03465.png">

**Comment by inspireui** [comment] 2017-09-04 03:08
Hi could you try this script to see if can be fixed: https://gist.github.com/inspireui/00e6f757c137b289c090173367c27af9

**Comment by Vrijlating** [comment] 2017-09-04 09:31
Hello,
unfortunately now appear another error:

Error: spawnSync /Users/Dario/Downloads/mstore.3.2.1/mstore-pro/node_modules/react-native/local-cli/setup_env.sh EACCES
    at exports._errnoException (util.js:1020:11)
    at spawnSync (child_process.js:450:20)
    at Object.execFileSync (child_process.js:487:13)
    at Object.run (/Users/Dario/Downloads/mstore.3.2.1/mstore-pro/node_modules/react-native/local-cli/cliEntry.js:136:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:117:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
MBP-di-Dario:mstore-pro Dario$

**Comment by inspireui** [comment] 2017-09-05 16:01
hi this error log is not a root cause, could you show your xcode red warning message ?

**Comment by Vrijlating** [comment] 2017-09-05 16:04
Hello,
I send you a screen of xcode

**Comment by inspireui** [comment] 2017-09-05 16:31
Hi, i can not see the attach from your comment, please upload it again

**Comment by Vrijlating** [comment] 2017-09-05 16:46
Hello,
tell me if you can see it now

2017-09-05 18:31 GMT+02:00 InspireUI <notifications@github.com>:

**Comment by inspireui** [comment] 2017-09-06 01:36
Hi, this is what i can see - https://gyazo.com/cf1f531f20a5472239fe03d9bd81fb1e, please try to update it to cloud and share your URL

**Comment by Vrijlating** [comment] 2017-09-06 07:44
Hello, i have upload it on image hosting site: https://ibb.co/c7Xvya

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-09-06 3:36 GMT+02:00 InspireUI <notifications@github.com>:

**Comment by inspireui** [comment] 2017-09-06 07:48
alright, i've got the issue, please try with this cmd: pwd 

It will print your current project path, please make sure is does not content any space " ", if yes please move the project folder to the new one which is not content space. This is an issue from React Native library (they have fixed on latest version).

**Comment by Vrijlating** [comment] 2017-09-06 07:53
I have try it now and unfortunately is not my case, I have copied here the
terminal text and the path don't have space


MBP-di-Dario:mstore-pro Dario$ pwd

/Users/Dario/Downloads/mstore.3.2-3.1/mstore-pro

MBP-di-Dario:mstore-pro Dario$


2017-09-06 9:48 GMT+02:00 InspireUI <notifications@github.com>:

**Comment by inspireui** [comment] 2017-09-06 07:59
Could you have a look to this guide - https://medium.com/@jjerryhan/handling-third-party-build-error-on-react-native-0-46x-445f867e7a2b

Try these cmd
> rm -rf ~/.rncache
> rm -rf node_modules
> yarn install
> react-native run-ios

**Comment by Vrijlating** [comment] 2017-09-06 08:03
This is what appear:
1 error generated.


** BUILD FAILED **


The following build commands failed:
	CompileC /Users/Dario/Downloads/mstore.3.2-3.1/mstore-pro/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/Objects-normal/x86_64/RCTFBSDKInitializer.o RCTFBSDK/core/RCTFBSDKInitializer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/beostore.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/beostore.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


MBP-di-Dario:mstore-pro Dario$ 

> Il giorno 06 set 2017, alle ore 09:59, InspireUI <notifications@github.com> ha scritto:
> 
> rm -rf ~/.rncache
> rm -rf node_modules
> yarn install
> react-native run-ios

**Comment by inspireui** [comment] 2017-09-06 08:06
Hi look like you have missing the facebook SDK as the guide - https://mstore.gitbooks.io/mstore-manual/content/chapter1.html

"For iOS, you need to download the FacebookSDK(https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip) and copy to ~/Documents/FacebookSDK."

**Comment by Vrijlating** [comment] 2017-09-06 08:12
Hello,
Thank you very much, pratically I has just placed the Facebook SDK in documents, but is necessary also to rename it, I have forgot this, thank you very much, now the demo start, I will try to update with my data, I will send you an email if I find other difficulties, thank you for patience and support

**Comment by inspireui** [comment] 2017-09-06 08:14
Great, i'm glad that it was help, sorry for the unclear document, i will highlight the FacebookSDK.

Please help us to give a rating from http://codecanyon.net/downloads and let us know if you have any further support. Thank you!

**Comment by Vrijlating** [comment] 2017-09-06 15:31
Hello,
unfortunately I am new here.
I have proceed to customize the app, but I have encountered some problem.
First of all I have make a new Wordpress installation only for test, so
there are only one article and one wocommerce product.
I have edited the constants.js and I think no problem in this.
When I launch the app there is some problem:

First of all you can see here:
https://ibb.co/iqGaya
In the homepage there are still products the are not present in my
installation, why?
P.S. i have place two circle on topper because I would know how I can edit
the color of icons

The second problem is this:
https://ibb.co/mEzjrv
About categories are correctly charged in the app, also the product in it
is ok, but it don't showing the products image, why?

Third:
https://ibb.co/mZ8zPF
Like the homepage, also in the news section there are content that are not
present in my site

Fourth:
https://ibb.co/hMbxBv
I can't work on the app in Xcode because there are always these 2 problem,
you know how I can solve it?

Fift:
In the Migrate Service of you guide, it will be used only when is used your
Wordpress installation for base, or is an essential step?



2017-09-06 10:14 GMT+02:00 InspireUI <notifications@github.com>:

**Comment by Vrijlating** [comment] 2017-09-08 07:14
Hello,
unfortunately I am new here.
I have proceed to customize the app, but I have encountered some problem.
First of all I have make a new Wordpress installation only for test, so there are only one article and one wocommerce product.
I have edited the constants.js and I think no problem in this.
When I launch the app there is some problem:

First of all you can see here:
https://ibb.co/iqGaya
In the homepage there are still products the are not present in my installation, why?
P.S. i have place two circle on topper because I would know how I can edit the color of icons

The second problem is this:
https://ibb.co/mEzjrv
About categories are correctly charged in the app, also the product in it is ok, but it don't showing the products image, why?

Third:
https://ibb.co/mZ8zPF
Like the homepage, also in the news section there are content that are not present in my site

Fourth:
https://ibb.co/hMbxBv
I can't work on the app in Xcode because there are always these 2 problem, you know how I can solve it?

Fift:
In the Migrate Service of you guide, it will be used only when is used your Wordpress installation for base, or is an essential step?


Dario Ditto
Inviato da iPhone

**Comment by inspireui** [comment] 2017-09-11 02:32
Sorry for lated response:

#1 - From the Constants.js file, there is the config "tagIdBanner" which is use to config the tag id for the banner on the homepage.

#2 - please try the related issue here for setting up the image - https://github.com/inspireui/mstore/issues/18 and the product display size guide - https://mstore.gitbooks.io/mstore-manual/content/chapter5.html

#3. Could be the network issues on the Android OS or Android SDK, please make sure your Android SDK is the same as with this guide - https://gyazo.com/5cc342b4111f066b3ba19b594c644e95

#4 Please try to this guide to setup your dev provisioning profile - https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppStoreDistributionTutorial/CreatingYourTeamProvisioningProfile/CreatingYourTeamProvisioningProfile.html

#5 It is used for released your app to Appstore or Google Play

Thank you!

**Comment by inspireui** [comment] 2017-09-27 00:59
Hi @Vrijlating could you help to check if you are happy to close this ticket, please also upgrade new v3.3.1 with latest build and hotfix. Thank you!

**Closed** 2017-10-05 05:30 UTC
Labels: help wanted
