### ISSUE TITLE
Product image not showing up

### ISSUE THREAD

**Issue by hazephase** [inspireui/mstore#18] opened 2017-07-20 07:46 UTC
const ThumbnailSizes = {
    CatalogImages: {
        width: 300,
        height: 360,
    },
    SingleProductImage: {
        width: 600,
        height: 720,
    },
    ProductThumbnails: {
        width: 180,
        height: 216,
    },
};

I used these setting for my WP backend but I am still unable to see the products image. I also used the regenerate thumbnails plugin

**Comment by alien3d** [comment] 2017-07-20 10:46
There's a few issue  there
1. Are you using the default image size work ?  
2. What platform you try ? OSX +android  ,OSX+iphone or Windows +Android
I'm success on OSX+Android + My Own Server only
iPhone still hassle and seem a lot of code when default render yarn pretty different with current . I'm still learning how Xcode work now..
Will document later iOS version later.. still thinking..

**Comment by bossanc** [comment] 2017-07-20 11:27
I have the same problem as you and sent mail to support.
In the picture is reply mail

![img2](https://user-images.githubusercontent.com/6060430/28414899-b1d0a71c-6d77-11e7-94aa-19aa20cb9e18.PNG)

**Comment by hazephase** [comment] 2017-07-21 04:53
@alien3d  Are you using the default image size work ?
Don't know what this means

What platform you try ?
I am using Windows Expo and testing on android

**Comment by bossanc** [comment] 2017-07-21 05:18
Hi @hazephase could you try to check the product image URL in you WP.

**Example**
yourdomian.com/wp-content/uploads/2017/07/image.jpg

Mstore GET 
yourdomian.com/wp-content/uploads/2017/07/image-300x360.jpg
yourdomian.com/wp-content/uploads/2017/07/image-600x720.jpg
yourdomian.com/wp-content/uploads/2017/07/image-180x216.jpg

If Mstore Get URL not found I think this is the cause of the problem.

**Comment by hazephase** [comment] 2017-07-21 07:09
OK, I corrected it, before I it was showing wp.yourdomian.com/wp-content/uploads/2017/07/image-300x360.jpg

**Comment by hazephase** [comment] 2017-07-21 11:29
but I am still getting this error

**Comment by inspireui** [comment] 2017-07-24 03:07
Closed as not an issue.

@hazepha please check your email to see the solution
The fixing is just ignore the resize image as your image URL is not work, example hosting/wp-content/uploads/2016/12/IMG_9202-1000x1000.jpg so you can use original image like - host/wp-content/uploads/2016/12/IMG_9202.jpg, by this update on Omni.js
<code>
export const getProductImage = (uri, containerWidth) => {
    return uri;
</code>

**Closed by inspireui** 2017-07-24 03:07 UTC
Labels: help wanted

**Comment by alien3d** [comment] 2017-07-24 04:09
@inspireui you shouldn't close yet .. I'm writing long  word and will be post why this bugs occour starting from 0

**Comment by inspireui** [comment] 2017-07-24 04:31
Hi @alien3d, we have checked from @hazephase's issue website and figured out from the image setting Wordpress site and response solution to his private email, your case could be other issue, feel free to open other ticket with your resolution that would be great ;)
