### ISSUE TITLE
No route was found

### ISSUE THREAD

**Issue by chamroeunbm** [inspireui/mstore#11] opened 2017-07-10 08:08 UTC
After updating to 3.1, i got this error when pointing to my WooCommerce. i already install JSON API and the other 2 plugin mentioned in the your doc.

https://ibb.co/hvWb7v

But i try version 3.0 and below, it worked fine.

**Comment by inspireui** [comment] 2017-07-10 15:09
Hi, please try with the website on this repos to check the issue, compare with this config - https://github.com/inspireui/mstore/blob/master/Constants.js. Thanks

**Comment by chamroeunbm** [comment] 2017-07-11 08:58
It worked fine with your website.  And it also used to work with my website when I use the older version of beostore

**Comment by minhcasi** [comment] 2017-07-11 09:48
Could you send your website to my email for checking support@inspireui.com. Thank you

**Comment by chamroeunbm** [comment] 2017-07-11 12:12
email sent

**Comment by minhcasi** [comment] 2017-07-12 14:26
Hi the issue is from the Wordpress setting, please check the Post name option from Setting to enable the Rest API
<img width="403" alt="screen shot 2017-07-12 at 9 24 22 pm" src="https://user-images.githubusercontent.com/1459805/28122497-905c2e9c-6748-11e7-8b97-2d2fee123ba5.png">

**Comment by mb1kh** [comment] 2017-07-14 07:50
Same issue(No route was found matching the URL and request method). even if i set Post name as you said, still error.


http://imgur.com/a/bpwWs

Please help

**Comment by inspireui** [comment] 2017-07-14 14:34
Hi, please make sure you can access the json from your website setting like from - http://mstore.io/wp-json/wc/v2

So, It could be caused by some other reason:
- The .htaccess or web server setting (rewrite mode)
- The Rest API from WooCommerce is not enable

**Comment by mb1kh** [comment] 2017-07-15 04:14
Maybe my Wordpress is too old.
My Wordpress v4.5 and Woommerce v2.6.1

What's the minimum requirement?

**Comment by inspireui** [comment] 2017-07-17 09:27
yes, that's the reason as the the Wordpress only support build in Rest API after v4.7, please try to install this plugins: https://wordpress.org/plugins/rest-api/ and some extra plugin base on this guide - https://mstore.gitbooks.io/mstore-manual/content/expo-version/wordpress-installing.html

**Comment by inspireui** [comment] 2017-07-19 02:28
I'm closing this ticket as it was an issue from the Wordpress setting, please reopen it if you still have an issue. Thank you

**Closed by inspireui** 2017-07-19 02:28 UTC
Labels: help wanted
